branches:
  - name: main
repositoryUrl: https://github.com/bert0RM/umami-client
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - type: feat
            section: ":sparkles: Features"
            hidden: false
          - type: fix
            section: ":lady_beetle: Bug Fixes"
            hidden: false
          - type: docs
            section: ":book: Documentation"
            hidden: false
          - type: style
            section: ":art: Styles"
            hidden: false
          - type: refactor
            section: ":recycle: Code Refactoring"
            hidden: false
          - type: perf
            section: ":zap: Performance Improvements"
            hidden: false
          - type: test
            section: ":white_check_mark: Tests"
            hidden: false
          - type: build
            section: ":package: Build System"
            hidden: false
          - type: ci
            section: ":construction: Continuous Integration"
            hidden: false
          - type: revert
            section: ":rewind: Reverts"
            hidden: false
          - type: chore
            hidden: true
  - - "@semantic-release/npm"
  - - "@semantic-release/github"
    - successComment: false
      failComment: false
