name: Release
on:
  workflow_dispatch:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
          node-version: '22'
      - name: Install deps
        run: |
          npm install -g semantic-release
          npm install -g conventional-changelog-conventionalcommits
      - name: Yarn install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            npx semantic-release
          else
            echo "ERR: Should only run on main"
            exit 1
          fi
        
